export type PostRow = {
  id: string;
  workspace_id: string;
  workspace_slug: string | null;
  post_id: string;
  title: string | null;
  description: string | null;
  status: string | null;
  publish_status: string | null;
  publish_date: string | null;
  publish_time: string | null;
  scheduled_at: string | null;
  platform: string | null;
  platform_targets: string[] | null;
  campaign_id: string | null;
  campaign_name: string | null;
  pillar: string | null;
  format: string | null;
  post_type: string | null;
  media_id: string | null;
  media_ids: string[] | null;
  media_url: string | null;
  media_type: string | null;
  media_filename: string | null;
  media_alt_text: string | null;
  storage_path: string | null;
  monday_item_id: string | null;
  monday_sync_status: string | null;
  published_at: string | null;
  metadata: Record<string, unknown> | null;
  created_at: string | null;
  updated_at: string | null;
};
